#!/bin/sh
# vim: set ft=sh

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

cd "${destination}"

echo "${BUILD_ID}" > build-id
echo "${BUILD_NAME}" > build-name
echo "${BUILD_JOB_NAME}" > build-job-name
echo "${BUILD_PIPELINE_NAME}" > build-pipeline-name
echo "${BUILD_TEAM_NAME}" > build-team-name
echo "${ATC_EXTERNAL_URL}" > atc-external-url

jq -n "{
    \"version\": { \"build_id\": \"${BUILD_ID}\" },
    \"metadata\": [
        { \"name\": \"BUILD_ID\", \"value\": \"${BUILD_ID}\" },
        { \"name\": \"BUILD_NAME\", \"value\": \"${BUILD_NAME}\" },
        { \"name\": \"BUILD_JOB_NAME\", \"value\": \"${BUILD_JOB_NAME}\" },
        { \"name\": \"BUILD_PIPELINE_NAME\", \"value\": \"${BUILD_PIPELINE_NAME}\" },
        { \"name\": \"BUILD_TEAM_NAME\", \"value\": \"${BUILD_TEAM_NAME}\" },
        { \"name\": \"ATC_EXTERNAL_URL\", \"value\": \"${ATC_EXTERNAL_URL}\" }
    ]
}" >&3
